# Generated by Django 6.0.2 on 2026-02-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField()),
                ('password', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRegestration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField()),
                ('password', models.CharField()),
                ('nikname', models.CharField()),
            ],
        ),
    ]
